pipeline:
  name:
    baseline

  components:
    - name: sentence_embedding
      parameters:
        model_path:
          all-MiniLM-L6-v2

    - name: embedding_similarity
      
    - name random_sampler:
      parameters:
        n: 0.1
        
    - name: llm_ensemble_labeler
      parameters:
        model_paths:
          - qwen2
          - llama3.1
          - gemma2
        temperature:
          0.0
        prompt_template:
          source: dataset[labeling_prompt_template]
        resolver: majority_vote
        threshold: 0.5
        concatenate_decisions_to_x: append

    - name: gml_visualizer
      parameters:
        output_file:
          labeled

    - name: gcn_propagator
      parameters:
        epochs:
          500
        patience:
          5
        
    - name: gml_visualizer
      parameters:
        output_file:
          propagated